import { type Text, text } from './text.js';

export const FLOOR_COUNT = 10;

export type ThemeId = 'warrens' | 'crypts' | 'depths' | 'lair';

export interface ThemeDef {
  id: ThemeId;
  name: Text;
  /** Room map art in apps/web/public/art/rooms; picked per Room by the Labyrinth seed. */
  maps: string[];
}

export const THEMES: Record<ThemeId, ThemeDef> = {
  warrens: { id: 'warrens', name: text('Goblin warrens', 'Гоблинские норы'), maps: ['goblins-1', 'goblins-2', 'goblins-3', 'goblins-4', 'goblins-5', 'goblins-6', 'goblins-7', 'goblins-8'] },
  crypts: { id: 'crypts', name: text('Undead crypts', 'Склепы нежити'), maps: ['crypt-1', 'crypt-2', 'crypt-3', 'crypt-4', 'crypt-5', 'crypt-6', 'crypt-7', 'crypt-8'] },
  depths: { id: 'depths', name: text('Demon-touched depths', 'Осквернённые демонами глубины'), maps: ['demons-1', 'demons-2', 'demons-3', 'demons-4', 'demons-5', 'demons-6', 'demons-7', 'demons-8'] },
  lair: { id: 'lair', name: text('The Dragon’s lair', 'Логово дракона'), maps: ['lair-1', 'lair-2', 'lair-3', 'lair-4', 'lair-5', 'lair-6'] },
};

/** Season 0 Floor themes (docs/design.md → The Labyrinth). */
export function themeOf(floor: number): ThemeId {
  if (floor <= 3) return 'warrens';
  if (floor <= 6) return 'crypts';
  if (floor <= 9) return 'depths';
  return 'lair';
}

/** Grid size: about 100 Rooms per Floor, a smaller lair at the bottom (v0). */
export function floorSize(floor: number): { width: number; height: number } {
  return floor >= FLOOR_COUNT ? { width: 6, height: 6 } : { width: 10, height: 10 };
}

export type RoomType =
  | 'landing' | 'stairs' | 'waypoint' | 'camp'
  | 'fight' | 'empty' | 'event' | 'treasure'
  | 'vault' | 'miniboss' | 'boss'
  /** Behind a secret Door: a hoard for whoever spots the way in. */
  | 'hidden'
  /** Behind a Twin door, which opens only for a Duo: the Twin Wardens and their Bond rings. */
  | 'twin'
  /** A quiet Room's standing stone where a Duo swears to share or take. */
  | 'oathstone';

/**
 * Season 0's first event kinds. Floors are generated by picking from this list, so
 * adding to it or reordering it would change the events of Labyrinths already made.
 */
export const FIRST_EVENT_KINDS = [
  'three-chests', 'shrine', 'gambler', 'merchant', 'trapped-corridor', 'cursed-altar', 'locked-cache', 'lockpicking',
  'fountain', 'prisoner', 'library', 'bone-pile', 'riddle',
] as const;
/** Kinds added later for the goblin warrens: rolled onto some of their event Rooms after a Floor is made (labyrinth.ts). */
export const WARREN_EVENT_KINDS = ['cookpot', 'webbed-body'] as const;
/** Kinds added later for the crypts and the depths, rolled the same way on their own seed. */
export const CRYPT_EVENT_KINDS = ['sarcophagus'] as const;
export const DEPTH_EVENT_KINDS = ['bargain'] as const;
/** And the Dragon's lair's own. */
export const LAIR_EVENT_KINDS = ['whispering-skulls', 'spilled-hoard', 'fallen-champion'] as const;
export const EVENT_KINDS = [...FIRST_EVENT_KINDS, ...WARREN_EVENT_KINDS, ...CRYPT_EVENT_KINDS, ...DEPTH_EVENT_KINDS, ...LAIR_EVENT_KINDS] as const;
export type EventKind = (typeof EVENT_KINDS)[number];

/**
 * What a Door says about the Room behind it. Fight Clues depend on the theme;
 * the rest are shared. Several per type so the same Floor doesn't repeat itself.
 */
export const CLUES: Record<RoomType, Text[] | Record<ThemeId, Text[]>> = {
  landing: [text('Footprints of everyone who came down before you', 'Следы всех, кто спускался до вас')],
  stairs: [text('A cold draft rising from below', 'Снизу тянет холодом'), text('Steps worn smooth, going down', 'Стёртые ступени уходят вниз')],
  waypoint: [text('A faint hum of old magic', 'Слабый гул древней магии'), text('Stones that glow like embers', 'Камни тлеют, как угли')],
  camp: [text('Old ashes and a cold hearth', 'Старая зола и холодный очаг'), text('The smell of stale bread and pipe smoke', 'Пахнет чёрствым хлебом и трубочным дымом')],
  fight: {
    warrens: [text('Growling and the smell of smoke', 'Рычание и запах дыма'), text('Crude laughter and clanking pots', 'Грубый смех и звон котелков')],
    crypts: [text('The scrape of bone on stone', 'Скрежет кости о камень'), text('A cold draft and a dry rattle', 'Холодный сквозняк и сухой стук')],
    depths: [text('Heat and the stink of sulfur', 'Жар и вонь серы'), text('Chains rattling in the dark', 'Звон цепей в темноте')],
    lair: [text('Claws on rock and hissing', 'Когти по камню и шипение'), text('Scales scraping the walls', 'Чешуя трётся о стены')],
  },
  empty: [text('Silence', 'Тишина'), text('Dust and nothing else', 'Пыль, и больше ничего'), text('Dripping water', 'Капает вода')],
  event: [text('Someone humming a tune', 'Кто-то напевает мотив'), text('Candlelight flickering under the door', 'Под дверью мерцает свеча'), text('A strange sweet smell', 'Странный сладкий запах')],
  treasure: [text('A faint golden glow', 'Слабое золотое сияние'), text('The glint of metal', 'Блеск металла')],
  vault: [text('Iron bands and a great lock', 'Железные обручи и огромный замок')],
  miniboss: [text('Something big breathing behind the door', 'За дверью дышит что-то большое'), text('Heavy footsteps and the smell of blood', 'Тяжёлые шаги и запах крови')],
  boss: [text('The heat of a dragon’s breath', 'Жар драконьего дыхания')],
  hidden: [text('A thin draft through a crack in the stones', 'Тонкий сквозняк из трещины в камнях'), text('Scratches on the wall, as if something slid here', 'Царапины на стене, будто здесь что-то сдвигали')],
  twin: [text('Two stone hands side by side, waiting for two more', 'Две каменные ладони рядом, будто ждут ещё двух'), text('Two voices humming one note behind the stone', 'За камнем два голоса тянут одну ноту')],
  oathstone: [text('A low hum, like two voices agreeing', 'Низкий гул, будто два голоса о чём-то условились'), text('Words cut into stone: “Share, or take”', 'Слова, высеченные в камне: «Поделись или возьми»')],
};

export function cluesFor(type: RoomType, theme: ThemeId): Text[] {
  const entry = CLUES[type];
  return Array.isArray(entry) ? entry : entry[theme];
}
