#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ
# Wizard library: delightful, consistent UX, identical across every wizard.
# в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%sв–ё Stage %s/%s В· %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %sвЂў%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %sвљ  %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %sв†— opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %sвњ“ wrote%s %s в†’ %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sвњ“ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sвњ“ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  вњ“ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђ
# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# First deploy of Dark Corner to the ugolok VPS. Run from the repo root in Git Bash:
#   bash scripts/setup-server.sh
# Values for the server's .env are collected in .env.server (git-ignored), then
# uploaded. The hub's SSO_SECRET is copied on the server and never touches this PC.
# Runbook and background: docs/deploy.md.

TOTAL_STAGES=9
ENV_FILE=".env.server"
REPO_SSH="git@github-darkcorner:IkayevAibar/DarkCorner.git"
DOMAIN="dark.ugolok.world"

# remote "command": shows a command, asks, then runs it on the server over SSH.
remote() {
  printf '\n  %s$ %s%s\n' "$DIM" "$1" "$RESET"
  if confirm "Run this on $SERVER?"; then
    ssh -o ConnectTimeout=15 "$SERVER" "$1"
  else
    SKIPPED+=("on the server: $1")
    warn "skipped — run it by hand later"
  fi
}

banner "Dark Corner: first deploy to $DOMAIN"

stage "Before you start"
say "The server deploys the main branch, so the week 1 and week 2 work must be merged."
open_url "https://github.com/IkayevAibar/DarkCorner/pulls"
step "Merge the pull requests for claude/week-1 and claude/week-2 into main."
confirm "Is that code on main now?" || { warn "Merge first, then run this again."; exit 1; }
SERVER=""
ask SERVER "Server to deploy to [root@92.38.49.9]:"
SERVER=${SERVER:-root@92.38.49.9}
if ssh -o BatchMode=yes -o ConnectTimeout=10 "$SERVER" true 2>/dev/null; then
  printf '  %s✓ SSH to %s works%s\n' "$GREEN" "$SERVER" "$RESET"
else
  warn "Can't SSH to $SERVER without a password prompt. Fix your SSH key, then re-run."
  exit 1
fi
pause

stage "DNS record for $DOMAIN"
say "Add one record where the other ugolok.world subdomains are managed."
step "Type A, name 'dark', value = the server's IP, default TTL."
step "Copy whatever proxy setting mc.ugolok.world uses (Caddy needs to get its own certificate)."
pause "Press Enter once the record is saved"
if nslookup "$DOMAIN" 2>/dev/null | grep -q "${SERVER#*@}"; then
  printf '  %s✓ %s already points at %s%s\n' "$GREEN" "$DOMAIN" "${SERVER#*@}" "$RESET"
else
  warn "$DOMAIN doesn't resolve to ${SERVER#*@} yet. That's fine: DNS can take a few minutes; carry on."
fi
pause

stage "Deploy key for the server"
say "The server pulls the repo with its own read-only key (one key per repo)."
remote "test -f /root/.ssh/deploy-darkcorner || ssh-keygen -t ed25519 -N '' -f /root/.ssh/deploy-darkcorner -C darkcorner-deploy -q; grep -q 'Host github-darkcorner' /root/.ssh/config || printf '\nHost github-darkcorner\n  HostName github.com\n  IdentityFile /root/.ssh/deploy-darkcorner\n  IdentitiesOnly yes\n' >> /root/.ssh/config; echo; cat /root/.ssh/deploy-darkcorner.pub"
open_url "https://github.com/IkayevAibar/DarkCorner/settings/keys/new"
step "Title: darkcorner VPS. Key: the line starting with ssh-ed25519 shown above."
step "Leave 'Allow write access' unticked, then click 'Add key'."
pause "Press Enter once the key is added"

stage "Clone the repo on the server"
remote "test -d /opt/darkcorner/.git || git clone $REPO_SSH /opt/darkcorner; cd /opt/darkcorner && git checkout main && git pull --ff-only && git log --oneline -1"
pause

stage "Values for the server's .env"
say "Passwords are generated here; the rest you look up once."
POSTGRES_PASSWORD=$(_existing POSTGRES_PASSWORD || true)
[[ -n "$POSTGRES_PASSWORD" ]] || POSTGRES_PASSWORD=$(openssl rand -hex 24)
SESSION_SECRET=$(_existing SESSION_SECRET || true)
[[ -n "$SESSION_SECRET" ]] || SESSION_SECRET=$(openssl rand -hex 32)
note "database password and session secret: generated"
step "Your Discord ID: Discord → Settings → Advanced → turn on Developer Mode,"
step "then right-click your own name anywhere → Copy User ID."
ask ADMIN_DISCORD_IDS "Paste your Discord user ID:"
step "Optional now, needed by week 5: a webhook for the channel that gets Broadcasts."
step "Channel → Edit channel → Integrations → Webhooks → New Webhook → Copy Webhook URL."
ask_secret DISCORD_WEBHOOK_URL "Paste the webhook URL (Enter to skip):"
write_env POSTGRES_USER "darkcorner"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env POSTGRES_DB "dark_corner"
write_env SESSION_SECRET "$SESSION_SECRET"
write_env PUBLIC_WEB_URL "https://$DOMAIN"
write_env ACCOUNT_ORIGIN "https://account.ugolok.world"
write_env ADMIN_DISCORD_IDS "$ADMIN_DISCORD_IDS"
write_env DISCORD_WEBHOOK_URL "$DISCORD_WEBHOOK_URL"
write_env SERVER_TIMEZONE "Asia/Almaty"
write_env WEB_BIND "172.17.0.1"
write_env WEB_PORT "8089"
write_env API_HOST_PORT "4002"
pause

stage "Upload the .env and add the hub's SSO secret"
say "Uploads $ENV_FILE as /opt/darkcorner/.env, then copies SSO_SECRET from the hub's .env on the server."
if confirm "Upload $ENV_FILE to $SERVER:/opt/darkcorner/.env?"; then
  scp -q "$ENV_FILE" "$SERVER:/opt/darkcorner/.env" && printf '  %s✓ uploaded%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("upload $ENV_FILE to /opt/darkcorner/.env")
fi
remote "cd /opt/darkcorner && (grep -q '^SSO_SECRET=.' .env || grep '^SSO_SECRET=' /opt/ugolok/.env >> .env) && chmod 600 .env && echo \"SSO_SECRET lines: \$(grep -c '^SSO_SECRET=.' .env)\""
pause

stage "Caddy: send $DOMAIN to Dark Corner"
say "Caddy lives in the Aetherbound repo (/opt/cardgame on the server). On your PC:"
step "Copy deploy/darkcorner.caddy to D:/RPG_DND_Game_website/docker/caddy-sites/darkcorner.caddy"
step "In D:/RPG_DND_Game_website/docker-compose.prod.yml, under the caddy service's environment:, add"
note "      DARKCORNER_DOMAIN: \${DARKCORNER_DOMAIN:-darkcorner.localhost}"
step "Commit and push that repo to main (or ask Claude to make this change there)."
pause "Press Enter once it's pushed"
say "Now on the server: pull it, set the domain, check the config, and restart Caddy."
warn "Restarting Caddy blips every ugolok site for a few seconds."
remote "cd /opt/cardgame && scripts/deploy.sh; grep -q '^DARKCORNER_DOMAIN=' .env || echo 'DARKCORNER_DOMAIN=$DOMAIN' >> .env; docker compose run --rm --no-deps -T caddy caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile && docker compose up -d caddy"
pause

stage "First deploy"
say "Builds the images and starts dc-postgres, dc-api and dc-web. Takes a few minutes."
remote "cd /opt/darkcorner && chmod +x scripts/*.sh && scripts/deploy.sh --force; docker ps --filter name=dc- --format '{{.Names}}  {{.Status}}'; curl -fsS 127.0.0.1:4002/api/health && echo"
pause

stage "Automatic deploys, backups, and a first visit"
remote "cp /opt/darkcorner/deploy/darkcorner-*.service /opt/darkcorner/deploy/darkcorner-*.timer /etc/systemd/system/ && systemctl daemon-reload && systemctl enable --now darkcorner-deploy.timer darkcorner-backup.timer && systemctl list-timers 'darkcorner-*' --no-pager"
open_url "https://$DOMAIN"
step "Sign in through the hub. You should arrive as an approved admin and can create a Hero."
step "Friends who sign in wait at the gate until you approve them: Account → Admin: players."
pause "Press Enter to finish"

finish
